# 1. Backpropagation for bias vectors (1.5 points)

In class, we discussed a multilayer perceptron (neural network) whose layers were all "dense", i.e. the output $a^m \in \mathbb{R}^{N^m}$ of the $m$th layer is computed as
\begin{align*}
z^m &= W^m a^{m - 1} + b^m \\
a^m &= \sigma^m(z^m)
\end{align*}
where $W^m \in \mathbb{R}^{N^m \times N^{m - 1}}$ is the weight matrix, $b^m \in \mathbb{R}^{N^m}$ is the bias vector, and $\sigma^m$ is the nonlinearity. We showed that
$$\frac{\partial C}{\partial W^m} = \frac{\partial C}{\partial z^m} a^{m - 1 \top}$$
Show that
$$\frac{\partial C}{\partial b^m} = \frac{\partial C}{\partial z^m}$$
Hint: The derivation is almost the same as for $W$.

### Answer 1

According to the chain rule, we can find $\frac{\partial C}{\partial b^m}$ by computing:
$$\frac{\partial C}{\partial b^m} = \frac{\partial C}{\partial z^m}\cdot \frac{\partial z^m}{\partial b^m}$$

Utilizing the same approach as in Lecture 4, we define:

$$\frac{\partial C}{\partial b^m_i} = \sum_{k=1}^{N^{m-1}}\frac{\partial C}{\partial z^m_k}\cdot \frac{\partial z^m_k}{\partial b^m_i}$$

$$ z_k^m = \sum_{l = 1}^{N^{m-1}} W_{kl}^m a_l^{m-1} + b_k^m $$

Therefore, when $i \neq k$, we have:

$$\frac{\partial z^m_k}{\partial b^m_i} = 0$$

Furthermore, when $i = k$, we have:

$$\frac{\partial z^m_i}{\partial b^m_i} = 1$$

Utilizing the matrix notation and multiplying $\frac{\partial C}{\partial z^m_i}$ by $\frac{\partial z^m_i}{\partial b^m_i}$ we have:

$$\frac{\partial C}{\partial b^m} = \frac{\partial C}{\partial z^m}$$



# 2. MLP from scratch (3.5 points)

Using numpy only, implement backward pass or a sigmoid MLP. Specifically, you will need to implement this functionality in the `train` function in the `SigmoidMLP` class below. You should write numpy code to populate the two lists `weight_gradients` and `bias_gradient`, where each entry in each list corresponds to the gradient for a weight matrix or bias vector for each layer. Then, when you run the code cell at the bottom of this notebook, the trained MLP should output (approximately) 0, 1, 1, 0, having learned the [XOR function](https://en.wikipedia.org/wiki/Exclusive_or). Please us a binary cross-entropy loss, i.e.
$$C(a^L, y) = (y - 1)\log(1 - a^L) - y\log(a^L)$$

*Note 1*: All layers in your model, including the last layer, will use the sigmoid nonlinearity. Remember that
$$
\frac{\partial}{\partial x}\mathrm{sigmoid}(x) = \mathrm{sigmoid}(x)(1 - \mathrm{sigmoid}(x))$$

*Note 2*: As we mentioned in class,
$$
\frac{\partial C}{\partial z^L} = a^L - y
$$

In [5]:
import numpy as np

class Layer:
    def __init__(self, inputs, outputs):
        # Initialize weight matrix and bias vector
        # Getting the initialization right can be tricky, but for this problem
        # simply drawing from a standard normal distribution should work.
        self.weights = np.random.randn(outputs, inputs)
        self.biases = np.random.randn(outputs, 1)
    def __call__(self, X):
        # Compute \sigmoid(Wx + b)
        return 1/(1 + np.exp(-(self.weights.dot(X) + self.biases)))

class SigmoidMLP:

    def __init__(self, layer_widths):
        self.layers = []
        for inputs, outputs in zip(layer_widths[:-1], layer_widths[1:]):
            self.layers.append(Layer(inputs, outputs))

    def train(self, inputs, targets, learning_rate):
        # Forward pass - compute each layer's output and store it for later use
        layer_outputs = [inputs]
        for layer in self.layers:
            layer_outputs.append(layer(layer_outputs[-1]))
        # Implement backward pass to populate weight_gradients and bias_gradients
        # lists here
        weight_gradients = []
        bias_gradients = []

        # ... (your code here) ...

        #todo

        # Perform gradient descent by applying updates
        for weight_gradient, bias_gradient, layer in zip(weight_gradients, bias_gradients, self.layers):
            layer.weights -= weight_gradient*learning_rate
            layer.biases -= bias_gradient*learning_rate

    def __call__(self, inputs):
        a = inputs
        for layer in self.layers:
            a = layer(a)
        return a

def train_mlp(n_iterations, learning_rate):
    mlp = SigmoidMLP([2, 2, 1])
    inputs = np.array([[0, 1, 0, 1],
                       [0, 0, 1, 1]])
    targets = np.array([[0, 1, 1, 0]])
    for _ in range(int(1e3)):
        mlp.train(inputs, targets, learning_rate)
    return mlp

In [ ]:
# You may need to change the n_iterations and learning_rate values
# but these worked for me
mlp = train_mlp(1, 1.)
#The following calls should result in (approximately) 0, 1, 1, 0
#If the outputs are somewhat close, your training has succeeded!
print(mlp(np.array([0, 0]).reshape(-1, 1)))
print(mlp(np.array([0, 1]).reshape(-1, 1)))
print(mlp(np.array([1, 0]).reshape(-1, 1)))
print(mlp(np.array([1, 1]).reshape(-1, 1)))

[[1.27741152]
 [0.98982489]]
[[ 0.00414142 -0.00976541 -0.01893494  0.00723064]
 [-0.00058631  0.00269728  0.00255646 -0.00076973]]
[[-1.07917603]]
[[ 0.00943404 -0.03431202 -0.032799    0.01123184]
 [-0.01923716  0.06996637  0.06688114 -0.02290309]]
